spring:
  application:
    name: pop-rocks
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.211.55.5:3306/pop_rocks?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: password
      filters: stat,wall,log4j,config # 配置监控统计拦截的filters，去掉后监控界面的SQL无法进行统计，wall用于防火墙
      max-active: 100 # 最大连接数
      initial-size: 1 # 初始化大小
      max-wait: 60000 # 获取连接等待时间
      min-idle: 1 # 最小连接数
      time-between-eviction-runs-millis: 60000 # 间隔多久进行一次检测，检测需要关闭的空闲连接，单位毫秒
      min-evictable-idle-time-millis: 300000 # 一个连接池中最小的生存时间，单位毫秒
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      stat-view-servlet:
        login-username: admin
        login-password: admin
        enabled: true
    #url: jdbc:mysql://10.211.55.5:3306/pop_rocks?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
server:
  port: 8081

